# Generated by Django 5.0.14 on 2026-04-27 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('entity', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField()),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1024, null=True)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['org_id', '-ts'], name='audit_log_org_ts'), models.Index(fields=['entity', 'entity_id', '-ts'], name='audit_log_entity_ts'), models.Index(fields=['actor_id', '-ts'], name='audit_log_actor_ts')],
            },
        ),
        migrations.CreateModel(
            name='PayrollAuditLedger',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('entity', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('prev_hash', models.CharField(max_length=64)),
                ('row_hash', models.CharField(max_length=64)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'payroll_audit_ledger',
                'indexes': [models.Index(fields=['org_id', 'seq'], name='payroll_ledger_org_seq')],
            },
        ),
    ]
