# Generated by Django 5.0.14 on 2026-04-27 16:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('default_currency', models.CharField(max_length=3)),
                ('default_timezone', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('country_code', models.CharField(max_length=2)),
                ('default_currency', models.CharField(max_length=3)),
                ('default_timezone', models.CharField(max_length=64)),
                ('default_locale', models.CharField(max_length=10)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('plan_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('federal', 'Federal'), ('state', 'State')], max_length=8)),
                ('state_code', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'ordering': ('country_code', 'date'),
                'indexes': [models.Index(fields=['country_code', 'date'], name='organizatio_country_d0d23d_idx')],
                'unique_together': {('country_code', 'date', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CountryLeaveTypeDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('default_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('statutory', models.BooleanField(default=False)),
                ('accrual_type', models.CharField(choices=[('annual', 'Annual'), ('monthly', 'Monthly'), ('event_based', 'Event-based'), ('none', 'No accrual')], max_length=16)),
            ],
            options={
                'unique_together': {('country_code', 'code')},
            },
        ),
    ]
