# Generated by Django 5.0.14 on 2026-05-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_department_head_employee_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryleavetypedefault',
            name='tenure_brackets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
