# Generated by Django 5.0.14 on 2026-05-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_country_leave_type_default_tenure_brackets'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_s3_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
