# Generated by Django 5.0.14 on 2026-08-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_logo_s3_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countryholiday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='countryholiday',
            name='observed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countryholiday',
            name='provisional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countryholiday',
            name='retrieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countryholiday',
            name='source',
            field=models.CharField(choices=[('official', 'Verified official government source'), ('provider', 'Imported provider data'), ('legacy', 'Legacy fixture fallback')], default='legacy', max_length=16),
        ),
        migrations.AddField(
            model_name='countryholiday',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='countryholiday',
            name='source_provider',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='countryholiday',
            name='source_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='countryholiday',
            name='subdivision_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='countryholiday',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_subdivision_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='countryholiday',
            unique_together={('country_code', 'date', 'name', 'source')},
        ),
        migrations.AddIndex(
            model_name='countryholiday',
            index=models.Index(fields=['country_code', 'subdivision_code', 'date'], name='organizatio_country_0a37eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='countryholiday',
            constraint=models.UniqueConstraint(condition=models.Q(('withdrawn_at__isnull', True), models.Q(('source_key', ''), _negated=True)), fields=('source_key', 'source'), name='country_holiday_unique_source_key_per_source'),
        ),
    ]
