# Generated by Django 5.0.14 on 2026-08-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_countryholiday_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryholiday',
            name='external_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='countryholiday',
            name='occurrence',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
