# Generated by Django 5.0.14 on 2026-08-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_countryholiday_external_id_countryholiday_occurrence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countryholiday',
            unique_together={('country_code', 'date', 'name', 'source', 'subdivision_code')},
        ),
    ]
