# Generated by Django 5.0.14 on 2026-07-03 08:19

import common.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('encryption', models.CharField(choices=[('none', 'None'), ('ssl', 'SSL/TLS'), ('starttls', 'STARTTLS')], default='starttls', max_length=10)),
                ('use_auth', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', common.fields.EncryptedCharField(blank=True, editable=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('connection_timeout', models.PositiveIntegerField(default=10)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('max_retry_attempts', models.PositiveIntegerField(default=3)),
                ('retry_interval_seconds', models.PositiveIntegerField(default=60)),
                ('signature', models.TextField(blank=True)),
                ('provider_preset', models.CharField(blank=True, max_length=32)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_message', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_configuration',
            },
        ),
    ]
