# Generated by Django 5.0.14 on 2026-07-28 13:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='accent_color',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='footer_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='header_html',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('key', models.CharField(max_length=64)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('html_body', models.TextField(blank=True)),
                ('text_body', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'email_template',
                'unique_together': {('org_id', 'key')},
            },
        ),
    ]
