# Generated by Django 5.0.14 on 2026-04-27 22:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimApproval',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('approver_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delegated', 'Delegated'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('delegated_to', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'claim_approval',
            },
        ),
        migrations.CreateModel(
            name='ClaimAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('s3_key', models.CharField(max_length=500)),
                ('uploaded_by', models.UUIDField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'claim_attachment',
            },
        ),
        migrations.CreateModel(
            name='ClaimCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('requires_attachment', models.BooleanField(default=True)),
                ('max_amount_per_claim', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency_code', models.CharField(default='MYR', max_length=3)),
            ],
            options={
                'db_table': 'claim_category',
            },
        ),
        migrations.CreateModel(
            name='ClaimPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('role_id', models.UUIDField(blank=True, null=True)),
                ('dept_id', models.UUIDField(blank=True, null=True)),
                ('annual_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approval_chain_code', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'claim_policy',
            },
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(default='MYR', max_length=3)),
                ('expense_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('merchant', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager approved'), ('finance_approved', 'Finance approved'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('current_level', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reimbursed_at', models.DateTimeField(blank=True, null=True)),
                ('reimbursement_reference', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'claim_request',
            },
        ),
        migrations.AddConstraint(
            model_name='claimcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('org_id', 'code'), name='claim_category_unique_code_per_org'),
        ),
        migrations.AddField(
            model_name='claimpolicy',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='claims.claimcategory'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='claims.claimcategory'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_requests', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='claimattachment',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='claims.claimrequest'),
        ),
        migrations.AddField(
            model_name='claimapproval',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='claims.claimrequest'),
        ),
        migrations.AddIndex(
            model_name='claimpolicy',
            index=models.Index(fields=['category'], name='claim_polic_categor_ba6758_idx'),
        ),
        migrations.AddIndex(
            model_name='claimrequest',
            index=models.Index(fields=['employee', '-submitted_at'], name='claim_reque_employe_bc09d4_idx'),
        ),
        migrations.AddIndex(
            model_name='claimrequest',
            index=models.Index(fields=['org_id', 'status'], name='claim_reque_org_id_ded6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='claimrequest',
            index=models.Index(fields=['status', 'current_level'], name='claim_reque_status_6fbc17_idx'),
        ),
        migrations.AddIndex(
            model_name='claimapproval',
            index=models.Index(fields=['claim', 'level'], name='claim_appro_claim_i_bf6859_idx'),
        ),
        migrations.AddIndex(
            model_name='claimapproval',
            index=models.Index(fields=['approver_id', 'status'], name='claim_appro_approve_782576_idx'),
        ),
    ]
