# Generated by Django 5.0.14 on 2026-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='business_justification',
            field=models.TextField(blank=True, default=''),
        ),
    ]
