# Generated by Django 5.0.14 on 2026-04-27 21:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('scope', models.CharField(choices=[('all', 'All'), ('leave', 'Leave'), ('claim', 'Claim')], max_length=8)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_delegations_as_delegate', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_delegations_as_delegator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_approval_delegation',
                'indexes': [models.Index(fields=['delegator', 'effective_from', 'effective_to'], name='workflow_ap_delegat_d14d62_idx'), models.Index(fields=['org_id'], name='workflow_ap_org_id_575d72_idx')],
            },
        ),
    ]
