# Generated by Django 5.0.14 on 2026-04-27 23:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_contribution', 'Employer contribution')], max_length=24)),
                ('is_statutory', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'payroll_component',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('bi_weekly', 'Bi-weekly')], max_length=16)),
                ('pay_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('locked', 'Locked'), ('published', 'Published')], default='draft', max_length=16)),
            ],
            options={
                'db_table': 'payroll_period',
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('uploaded_by', models.UUIDField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('row_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('csv_s3_key', models.CharField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payroll_run',
            },
        ),
        migrations.CreateModel(
            name='PayslipRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('employee_id', models.UUIDField()),
                ('gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.JSONField(blank=True, default=dict)),
                ('net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(default='MYR', max_length=3)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('pdf_s3_key', models.CharField(blank=True, max_length=500)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sent', 'Sent')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('csv_import', 'CSV import'), ('manual', 'Manual')], max_length=16)),
            ],
            options={
                'db_table': 'payslip_record',
            },
        ),
        migrations.AddConstraint(
            model_name='payrollcomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('org_id', 'code'), name='payroll_component_unique_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['org_id', '-period_start'], name='payroll_per_org_id_2f262e_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('org_id', 'period_start', 'period_end'), name='payroll_period_unique_dates_per_org'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='payslip.payrollperiod'),
        ),
        migrations.AddField(
            model_name='paysliprecord',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payslip.payrollperiod'),
        ),
        migrations.AddIndex(
            model_name='paysliprecord',
            index=models.Index(fields=['employee_id', '-period_id'], name='payslip_rec_employe_afbfb3_idx'),
        ),
        migrations.AddIndex(
            model_name='paysliprecord',
            index=models.Index(fields=['org_id', 'status'], name='payslip_rec_org_id_0e3d22_idx'),
        ),
        migrations.AddConstraint(
            model_name='paysliprecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee_id', 'period'), name='payslip_unique_emp_period'),
        ),
    ]
