# Generated by Django 5.0.14 on 2026-06-19 22:26
# Maps legacy PayrollPeriod.status values onto the new 5-state workflow:
#   locked    -> approved   (period finalized, pre-publish)
#   published -> completed  (payslips published)

from django.db import migrations


def forward(apps, schema_editor):
    PayrollPeriod = apps.get_model("payslip", "PayrollPeriod")
    PayrollPeriod.objects.filter(status="locked").update(status="approved")
    PayrollPeriod.objects.filter(status="published").update(status="completed")


def backward(apps, schema_editor):
    PayrollPeriod = apps.get_model("payslip", "PayrollPeriod")
    PayrollPeriod.objects.filter(status="approved").update(status="locked")
    PayrollPeriod.objects.filter(status="completed").update(status="published")


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0002_payrollperiod_approved_at_payrollperiod_completed_at_and_more'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
