# Generated by Django 5.0.14 on 2026-06-19 22:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0003_map_legacy_period_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('employee_id', models.UUIDField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('missing_bank', 'Missing bank'), ('negative_net', 'Negative net'), ('tax_mismatch', 'Tax mismatch'), ('other', 'Other')], default='other', max_length=16)),
                ('message', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('resolved_by', models.UUIDField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='payslip.payrollperiod')),
            ],
            options={
                'db_table': 'payroll_exception',
                'indexes': [models.Index(fields=['org_id', 'status'], name='payroll_exc_org_id_26dd4b_idx')],
            },
        ),
    ]
