# Generated by Django 5.0.14 on 2026-07-06 11:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _publish_existing(apps, schema_editor):
    """Existing announcements already have a published_at — keep them visible."""
    Announcement = apps.get_model("announcements", "Announcement")
    Announcement.objects.filter(status="draft", published_at__isnull=False).update(
        status="published"
    )


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('s3_key', models.CharField(max_length=500)),
                ('uploaded_by', models.UUIDField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'announcement_attachment',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'announcement_read',
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='audience_spec',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='announcement',
            name='audience_type',
            field=models.CharField(choices=[('all', 'Everyone'), ('departments', 'Departments'), ('roles', 'Roles'), ('teams', 'Teams'), ('employees', 'Specific employees')], default='all', max_length=16),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=8),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['org_id', 'status'], name='announcemen_org_id_8c9843_idx'),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='announcementread',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='announcements.announcement'),
        ),
        migrations.AddConstraint(
            model_name='announcementread',
            constraint=models.UniqueConstraint(fields=('announcement', 'user_id'), name='announcement_read_unique'),
        ),
        migrations.RunPython(_publish_existing, _noop),
    ]
