# Generated by Django 5.0.14 on 2026-04-28 09:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('report_code', models.CharField(max_length=64)),
                ('filters', models.JSONField(default=dict)),
                ('format', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_export_job',
                'indexes': [models.Index(fields=['user', '-created_at'], name='report_expo_user_id_5c3e35_idx'), models.Index(fields=['status'], name='report_expo_status_ef6564_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('filters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_saved_view',
                'indexes': [models.Index(fields=['user', 'report_code'], name='report_save_user_id_9a31e5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='savedview',
            constraint=models.UniqueConstraint(fields=('user', 'report_code', 'name'), name='saved_view_unique_user_report_name'),
        ),
    ]
