# Generated by Django 5.0.14 on 2026-07-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
