# Generated by Django 5.0.14 on 2026-08-24 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_delete_auth_login_prefs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cc_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='NotificationRouting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('type', models.CharField(max_length=64)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('delivery', models.CharField(choices=[('auto', 'Auto'), ('immediate', 'Immediate'), ('digest', 'Digest')], default='auto', max_length=16)),
                ('cc_entries', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_routing',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationrouting',
            constraint=models.UniqueConstraint(fields=('org_id', 'type'), name='notification_routing_unique_org_type'),
        ),
    ]
