#!/usr/bin/env bash
# HRMS first-boot bootstrap.
#
# What this does:
#   1. Generates a .env at repo root if missing (with fresh secrets).
#   2. Brings up the Docker stack (postgres, redis, minio, api, worker, beat, web, nginx).
#   3. Waits for the API to become ready.
#   4. Runs Django migrations.
#   5. Seeds the Provintell org, departments, employees, shifts, holidays, leave balances.
#   6. Prompts for the first HR admin's email + password and creates the account.
#
# Idempotent — safe to re-run. Existing .env, migrations, seed rows, and admin user are preserved.
#
# Usage:
#   deploy/bootstrap.sh           # production (uses docker-compose.prod.yml)
#   deploy/bootstrap.sh --dev     # development (compose only, DEBUG=1)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

MODE="prod"
if [[ "${1:-}" == "--dev" ]]; then
    MODE="dev"
fi

COMPOSE_FILES=(-f deploy/docker-compose.yml)
if [[ "$MODE" == "prod" ]]; then
    COMPOSE_FILES+=(-f deploy/docker-compose.prod.yml)
fi

log()  { printf "\033[1;34m[bootstrap]\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m[bootstrap]\033[0m %s\n" "$*"; }
err()  { printf "\033[1;31m[bootstrap]\033[0m %s\n" "$*" >&2; }

dc() { docker compose "${COMPOSE_FILES[@]}" "$@"; }

#-----------------------------------------------------------------------------
# 0. Preflight
#-----------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
    err "docker is not installed. Install it first (sudo apt install docker.io docker-compose-v2)."
    exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
    err "'docker compose' plugin not available. Install docker-compose-v2."
    exit 1
fi

#-----------------------------------------------------------------------------
# 1. Generate .env if missing
#-----------------------------------------------------------------------------
if [[ ! -f .env ]]; then
    log "No .env found — generating one with fresh secrets ($MODE mode)."

    # Need python with the cryptography package to generate a Fernet key.
    # Use the api image (it has cryptography installed) once it's pulled.
    # For first run, fall back to host python3 if available.
    if command -v python3 >/dev/null 2>&1 && python3 -c "from cryptography.fernet import Fernet" 2>/dev/null; then
        FERNET_KEY="$(python3 -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')"
    else
        log "Pulling api image to generate encryption key..."
        dc pull api >/dev/null
        FERNET_KEY="$(dc run --rm --no-deps api uv run python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())' | tr -d '\r\n')"
    fi

    SECRET_KEY="$(LC_ALL=C tr -dc 'a-zA-Z0-9!@#$%^&*()_+-=' </dev/urandom | head -c 64)"
    DB_PASSWORD="$(LC_ALL=C tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 32)"
    S3_SECRET="$(LC_ALL=C tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 32)"

    if [[ "$MODE" == "prod" ]]; then
        DEBUG=0
        SETTINGS=hrms_api.settings.prod
        ALLOWED_HOSTS="localhost,api"   # operator should edit this for their domain
        VITE_API="/api"
    else
        DEBUG=1
        SETTINGS=hrms_api.settings.dev
        ALLOWED_HOSTS="localhost,127.0.0.1,api"
        VITE_API="http://localhost:8000"
    fi

    cat > .env <<EOF
# Generated by deploy/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Mode: $MODE
#
# WARNING: HRMS_FIELD_ENCRYPTION_KEY encrypts IC, bank, EPF/SOCSO/EIS, LHDN data.
# Losing it means losing access to those fields forever. Back this file up
# offline (password manager / encrypted USB) before going live.

# === Django ===
DJANGO_SETTINGS_MODULE=$SETTINGS
DJANGO_SECRET_KEY=$SECRET_KEY
DJANGO_DEBUG=$DEBUG
DJANGO_ALLOWED_HOSTS=$ALLOWED_HOSTS

# === Field-level encryption (32-byte url-safe base64) ===
HRMS_FIELD_ENCRYPTION_KEY=$FERNET_KEY

# === Database ===
POSTGRES_USER=hrms
POSTGRES_PASSWORD=$DB_PASSWORD
POSTGRES_DB=hrms
DATABASE_URL=postgres://hrms:$DB_PASSWORD@postgres:5432/hrms

# === Redis ===
REDIS_URL=redis://redis:6379/0
CELERY_BROKER_URL=redis://redis:6379/1
CELERY_RESULT_BACKEND=redis://redis:6379/2

# === Object storage ===
S3_ENDPOINT_URL=http://minio:9000
S3_ACCESS_KEY=hrms
S3_SECRET_KEY=$S3_SECRET
S3_BUCKET=hrms
S3_REGION=us-east-1
S3_USE_SSL=0

# === Email — REPLACE with real SMTP for prod ===
SMTP_HOST=mailhog
SMTP_PORT=1025
SMTP_USER=
SMTP_PASSWORD=
SMTP_USE_TLS=0
DEFAULT_FROM_EMAIL=hrms@provintell.local

# === Frontend ===
VITE_API_BASE_URL=$VITE_API
EOF

    chmod 600 .env
    log ".env written (mode=$MODE)."
    if [[ "$MODE" == "prod" ]]; then
        warn "Edit .env now to set: DJANGO_ALLOWED_HOSTS, SMTP_*, DEFAULT_FROM_EMAIL."
        warn "Back up HRMS_FIELD_ENCRYPTION_KEY offline before continuing."
        read -rp "Press Enter when .env is ready, or Ctrl-C to abort..."
    fi
else
    log ".env already exists — keeping it."
fi

#-----------------------------------------------------------------------------
# 2. Bring up the stack
#-----------------------------------------------------------------------------
log "Starting stack (this may take a minute on first run)..."
dc up -d

#-----------------------------------------------------------------------------
# 3. Wait for API readiness
#-----------------------------------------------------------------------------
log "Waiting for API to become ready..."
for i in $(seq 1 60); do
    if dc exec -T api curl -sf http://localhost:8000/health/ready >/dev/null 2>&1; then
        log "API is ready."
        break
    fi
    if [[ $i -eq 60 ]]; then
        err "API did not become ready within 5 minutes."
        err "Check logs: docker compose ${COMPOSE_FILES[*]} logs api"
        exit 1
    fi
    sleep 5
done

#-----------------------------------------------------------------------------
# 4. Migrate
#-----------------------------------------------------------------------------
log "Running migrations..."
dc exec -T api uv run python manage.py migrate --noinput

#-----------------------------------------------------------------------------
# 5. Seed Provintell
#-----------------------------------------------------------------------------
log "Seeding Provintell org, departments, employees, shifts, holidays..."
SEED_FLAGS=()
if [[ "$MODE" == "prod" ]]; then
    SEED_FLAGS+=(--prod)
fi
dc exec -T api uv run python manage.py seed_provintell "${SEED_FLAGS[@]}"

#-----------------------------------------------------------------------------
# 6. First admin user
#-----------------------------------------------------------------------------
echo
log "Create the first HR admin account (skip with empty email if already done)."

read -rp "  Admin email: " ADMIN_EMAIL
if [[ -z "$ADMIN_EMAIL" ]]; then
    warn "Skipping admin creation."
else
    while :; do
        read -rsp "  Admin password (min 12 chars): " ADMIN_PW; echo
        read -rsp "  Confirm password:           "  ADMIN_PW2; echo
        if [[ "$ADMIN_PW" != "$ADMIN_PW2" ]]; then
            warn "Passwords do not match. Try again."
            continue
        fi
        if [[ ${#ADMIN_PW} -lt 12 ]]; then
            warn "Password must be at least 12 characters."
            continue
        fi
        break
    done

    log "Creating admin '$ADMIN_EMAIL' with org_admin role..."
    ADMIN_EMAIL="$ADMIN_EMAIL" ADMIN_PW="$ADMIN_PW" dc exec -T -e ADMIN_EMAIL -e ADMIN_PW api uv run python manage.py shell <<'PYEOF'
import os
from modules.identity.models import User, Role, UserRole
from modules.organization.models import Organization

email = os.environ["ADMIN_EMAIL"].strip().lower()
password = os.environ["ADMIN_PW"]

org = Organization.objects.get(slug="provintell")
user, created = User.objects.get_or_create(
    email=email,
    org_id=org.id,
    defaults={"is_staff": True, "is_active": True},
)
user.is_staff = True
user.is_active = True
user.set_password(password)
user.save()

role = Role.objects.filter(org_id=org.id, code="org_admin").first()
if role and not UserRole.objects.filter(user=user, role=role).exists():
    UserRole.objects.create(user=user, role=role, granted_by=None)

print(f"  -> {'created' if created else 'updated'}: {email}")
PYEOF
fi

#-----------------------------------------------------------------------------
# 7. Done
#-----------------------------------------------------------------------------
echo
log "Bootstrap complete."
echo
cat <<EOF
Next steps:
  1. Open the web UI:
       $( [[ "$MODE" == "prod" ]] && echo "https://<your-domain>/" || echo "http://localhost:5173/" )
  2. Sign in with the admin account you just created.
  3. Enrol TOTP MFA from /me/profile and save your recovery codes.
  4. Walk through one of each: leave request, claim, payslip, KPI assignment.
  5. Schedule the nightly backup:
       0 2 * * *  $REPO_ROOT/deploy/backups/nightly-pgdump.sh
  6. Read docs/runbooks/ — especially parallel-run-protocol.md before cut-over.

Useful commands:
  docker compose ${COMPOSE_FILES[*]} logs -f api
  docker compose ${COMPOSE_FILES[*]} ps
  docker compose ${COMPOSE_FILES[*]} down

To re-run this bootstrap (idempotent): deploy/bootstrap.sh${MODE:+ --$MODE}
EOF
