# Generated by Django 5.0.14 on 2026-04-27 19:20

import common.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('employee_code', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('alt_phone', models.CharField(blank=True, max_length=32)),
                ('ic_number', common.fields.EncryptedCharField(blank=True, editable=True, null=True)),
                ('ic_last4', models.CharField(blank=True, max_length=4)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undisclosed', 'Undisclosed')], max_length=16)),
                ('nationality', models.CharField(max_length=2)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=16)),
                ('religion', models.CharField(blank=True, max_length=32)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=2)),
                ('role_title', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('contract', 'Contract'), ('intern', 'Intern')], max_length=16)),
                ('schedule_type', models.CharField(choices=[('fixed', 'Fixed'), ('shift', 'Shift')], default='fixed', max_length=8)),
                ('hire_date', models.DateField()),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account_number', common.fields.EncryptedCharField(blank=True, editable=True, null=True)),
                ('bank_account_last4', models.CharField(blank=True, max_length=4)),
                ('lhdn_tax_no', common.fields.EncryptedCharField(blank=True, editable=True, null=True)),
                ('epf_no', common.fields.EncryptedCharField(blank=True, editable=True, null=True)),
                ('socso_no', common.fields.EncryptedCharField(blank=True, editable=True, null=True)),
                ('eis_no', common.fields.EncryptedCharField(blank=True, editable=True, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('on_leave', 'On leave'), ('terminated', 'Terminated'), ('resigned', 'Resigned')], default='active', max_length=16)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('locale', models.CharField(blank=True, max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employee.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_employee',
                'indexes': [models.Index(fields=['org_id', 'status'], name='employee_em_org_id_c6defa_idx'), models.Index(fields=['department_id'], name='employee_em_departm_e1e10e_idx'), models.Index(fields=['manager_id'], name='employee_em_manager_0d5e09_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('org_id', 'employee_code'), name='employee_unique_code_per_org'),
        ),
    ]
