# Generated by Django 5.0.14 on 2026-05-01 16:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=64)),
                ('sort_order', models.IntegerField(default=0)),
                ('min_headcount', models.IntegerField(blank=True, null=True)),
                ('parent_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='employee.team')),
            ],
            options={
                'db_table': 'employee_team',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='employee.team'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['org_id', 'sort_order'], name='employee_te_org_id_308243_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('org_id', 'name'), name='team_unique_name_per_org'),
        ),
    ]
