# Generated by Django 5.0.14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="photo_s3_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
