# Generated by Django 5.0.14 on 2026-06-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resignation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
