# Generated by Django 5.0.14 on 2026-07-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_personal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
