# Generated by Django 5.0.14 on 2026-06-30 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('employee_id', models.UUIDField()),
                ('mandays', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('billing_quarter', models.CharField(blank=True, max_length=8)),
                ('payout_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], max_length=12)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incentive_claim',
            },
        ),
        migrations.CreateModel(
            name='EmployeeBond',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('employee_id', models.UUIDField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('terms_version', models.CharField(default='v1', max_length=32)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incentive_employee_bond',
            },
        ),
        migrations.CreateModel(
            name='MandayLedger',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('to_employee_id', models.UUIDField(blank=True, null=True)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ledger_type', models.CharField(choices=[('pool_topup', 'Pool top-up'), ('claim_payout', 'Claim payout'), ('reclaimed', 'Reclaimed')], max_length=16)),
                ('source_seq', models.BigIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'incentive_manday_ledger',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('budget_mandays', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manager_id', models.UUIDField()),
                ('include_soc', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=12)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incentive_project',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incentive_customer',
                'indexes': [models.Index(fields=['org_id', 'is_active'], name='incentive_c_org_id_604340_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeebond',
            constraint=models.UniqueConstraint(fields=('org_id', 'employee_id'), name='uniq_bond_per_employee'),
        ),
        migrations.AddField(
            model_name='mandayledger',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_rows', to='incentive.claim'),
        ),
        migrations.AddField(
            model_name='mandayledger',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_rows', to='incentive.customer'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='incentive.customer'),
        ),
        migrations.AddField(
            model_name='mandayledger',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_rows', to='incentive.project'),
        ),
        migrations.AddField(
            model_name='claim',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='incentive.project'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['org_id', 'status'], name='incentive_p_org_id_bb85df_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['customer', 'status'], name='incentive_p_custome_f97c72_idx'),
        ),
        migrations.AddIndex(
            model_name='mandayledger',
            index=models.Index(fields=['org_id', 'to_employee_id'], name='incentive_m_org_id_7c4817_idx'),
        ),
        migrations.AddIndex(
            model_name='mandayledger',
            index=models.Index(fields=['customer', 'ledger_type'], name='incentive_m_custome_265b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='mandayledger',
            index=models.Index(fields=['project', 'ledger_type'], name='incentive_m_project_9e7ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['org_id', 'employee_id', 'status'], name='incentive_c_org_id_698609_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['project', 'status'], name='incentive_c_project_cc3497_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['org_id', 'billing_quarter', 'payout_status'], name='incentive_c_org_id_48a00f_idx'),
        ),
    ]
