# Generated by Django 5.0.14 on 2026-06-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
