# Generated by Django 5.0.14 on 2026-07-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0002_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='manager_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
