"""Generate the frontend notification label/security constants from the registry."""

import re
from pathlib import Path

from django.core.management.base import BaseCommand

from modules.notification.registry import DOMAIN_LABELS, REGISTRY


def _render() -> str:
    lines = [
        "// GENERATED by `python manage.py export_notification_registry` — DO NOT EDIT.",
        "// Source of truth: apps/api/modules/notification/registry.py",
        "",
        "export const EVENT_LABELS: Record<string, string> = {",
    ]
    for n in REGISTRY:
        lines.append(f"  {_key(n.type)}: {_str(n.label)},")
    lines.append("}")
    lines.append("")
    lines.append("export const DOMAIN_LABELS: Record<string, string> = {")
    for domain, label in DOMAIN_LABELS.items():
        lines.append(f"  {_key(domain)}: {_str(label)},")
    lines.append("}")
    lines.append("")
    lines.append("export const SECURITY_TYPES: ReadonlySet<string> = new Set([")
    for n in REGISTRY:
        if n.security:
            lines.append(f"  {_str(n.type)},")
    lines.append("])")
    lines.append("")
    lines.append("export function getEventLabel(type: string): string {")
    lines.append("  return EVENT_LABELS[type] ?? type")
    lines.append("}")
    lines.append("")
    lines.append("export function getDomainLabel(domain: string): string {")
    lines.append("  return DOMAIN_LABELS[domain] ?? domain")
    lines.append("}")
    lines.append("")
    lines.append("export function eventDomain(type: string): string {")
    lines.append('  return type.split(".")[0] ?? type')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


_IDENT = re.compile(r"[A-Za-z_$][\w$]*")


def _key(s: str) -> str:
    # Unquoted for valid JS identifiers (biome useLiteralKeys); quoted otherwise
    # (e.g. dotted event types like "leave.approved").
    return s if _IDENT.fullmatch(s) else f'"{s}"'


def _str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


class Command(BaseCommand):
    help = "Emit event-labels.generated.ts for the frontend from the notification registry."

    def add_arguments(self, parser):
        parser.add_argument("--output", default="", help="File path (default: stdout)")

    def handle(self, *args, **options) -> None:
        ts = _render()
        out = options["output"]
        if out:
            Path(out).write_text(ts)
            self.stdout.write(self.style.SUCCESS(f"wrote {out}"))
        else:
            self.stdout.write(ts)
