# Generated by Django 5.0.14 on 2026-06-23 23:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('task', 'Task'), ('acknowledge', 'Acknowledge')], default='task', max_length=16)),
                ('link_url', models.CharField(blank=True, max_length=1000)),
                ('link_target', models.CharField(choices=[('none', 'None'), ('internal', 'Internal'), ('external', 'External')], default='none', max_length=16)),
                ('default_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assignment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org_id', 'status'], name='assignment_org_id_c63524_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssignmentRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_ip', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='assignments.assignment')),
            ],
            options={
                'db_table': 'assignment_recipient',
                'indexes': [models.Index(fields=['employee_id', 'status'], name='assignment__employe_dac09e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='assignmentrecipient',
            constraint=models.UniqueConstraint(fields=('assignment', 'employee_id'), name='assignment_recipient_unique'),
        ),
    ]
