# Generated by Django 5.0.14 on 2026-06-24 09:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('acknowledge', 'Acknowledge'), ('questionnaire', 'Questionnaire')], default='task', max_length=16),
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=500)),
                ('qtype', models.CharField(choices=[('single_choice', 'Single choice'), ('multi_choice', 'Multiple choice'), ('short_text', 'Short text'), ('rating', 'Rating (1-5)')], default='single_choice', max_length=16)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment')),
            ],
            options={
                'db_table': 'assignment_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('answer', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assignments.assignmentquestion')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assignments.assignmentrecipient')),
            ],
            options={
                'db_table': 'assignment_response',
            },
        ),
        migrations.AddConstraint(
            model_name='assignmentresponse',
            constraint=models.UniqueConstraint(fields=('recipient', 'question'), name='assignment_response_unique'),
        ),
    ]
