# Generated by Django 5.0.14 on 2026-06-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_is_template_assignment_next_run_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='complete_on',
            field=models.CharField(default='manual', max_length=32),
        ),
    ]
