# Generated by Django 5.0.14 on 2026-06-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_complete_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='requires_evidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignmentrecipient',
            name='acked_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignmentrecipient',
            name='evidence_s3_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
