# Generated by Django 5.0.14 on 2026-07-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignment_requires_evidence_assignment_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentrecipient',
            name='last_reminded_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
