/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_mfa_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["auth_mfa_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_mfa_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_mfa_enable_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_password_forgot_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["departments_list"];
        put?: never;
        post: operations["departments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["departments_retrieve"];
        put: operations["departments_update"];
        post?: never;
        delete: operations["departments_destroy"];
        options?: never;
        head?: never;
        patch: operations["departments_partial_update"];
        trace?: never;
    };
    "/api/v1/employees/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description HR-facing employee CRUD. */
        get: operations["employees_list"];
        put?: never;
        /** @description HR-facing employee CRUD. */
        post: operations["employees_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description HR-facing employee CRUD. */
        get: operations["employees_retrieve"];
        /** @description HR-facing employee CRUD. */
        put: operations["employees_update"];
        post?: never;
        /** @description HR-facing employee CRUD. */
        delete: operations["employees_destroy"];
        options?: never;
        head?: never;
        /** @description HR-facing employee CRUD. */
        patch: operations["employees_partial_update"];
        trace?: never;
    };
    "/api/v1/employees/{id}/direct-reports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description HR-facing employee CRUD. */
        get: operations["employees_direct_reports_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{id}/probation-status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description HR-facing employee CRUD. */
        get: operations["employees_probation_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{id}/reporting-chain/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description HR-facing employee CRUD. */
        get: operations["employees_reporting_chain_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description HR-facing employee CRUD. */
        get: operations["employees_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description HR-facing employee CRUD. */
        patch: operations["employees_me_partial_update"];
        trace?: never;
    };
    "/api/v1/leave/balances/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["leave_balances_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/balances/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["leave_balances_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/balances/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["leave_balances_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/requests/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["leave_requests_list"];
        put?: never;
        post: operations["leave_requests_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/requests/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["leave_requests_retrieve"];
        put: operations["leave_requests_update"];
        post?: never;
        delete: operations["leave_requests_destroy"];
        options?: never;
        head?: never;
        patch: operations["leave_requests_partial_update"];
        trace?: never;
    };
    "/api/v1/leave/requests/{id}/approve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leave_requests_approve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/requests/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leave_requests_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/requests/{id}/reject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leave_requests_reject_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/requests/{id}/submit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leave_requests_submit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/requests/{id}/withdraw/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leave_requests_withdraw_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["leave_types_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leave/types/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["leave_types_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET/PATCH the current user's organization settings. */
        get: operations["org_settings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description GET/PATCH the current user's organization settings. */
        patch: operations["org_settings_partial_update"];
        trace?: never;
    };
    "/api/v1/organizations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Phase 1: read-only org view at /api/v1/organizations/. */
        get: operations["organizations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Phase 1: read-only org view at /api/v1/organizations/. */
        get: operations["organizations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/holidays/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schedule_holidays_list"];
        put?: never;
        post: operations["schedule_holidays_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/holidays/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schedule_holidays_retrieve"];
        put: operations["schedule_holidays_update"];
        post?: never;
        delete: operations["schedule_holidays_destroy"];
        options?: never;
        head?: never;
        patch: operations["schedule_holidays_partial_update"];
        trace?: never;
    };
    "/api/v1/schedule/shift-assignments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schedule_shift_assignments_list"];
        put?: never;
        post: operations["schedule_shift_assignments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/shift-assignments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schedule_shift_assignments_retrieve"];
        put: operations["schedule_shift_assignments_update"];
        post?: never;
        delete: operations["schedule_shift_assignments_destroy"];
        options?: never;
        head?: never;
        patch: operations["schedule_shift_assignments_partial_update"];
        trace?: never;
    };
    "/api/v1/schedule/shift-assignments/bulk-pattern/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["schedule_shift_assignments_bulk_pattern_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/shift-assignments/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schedule_shift_assignments_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/shift-assignments/publish/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["schedule_shift_assignments_publish_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/shifts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schedule_shifts_list"];
        put?: never;
        post: operations["schedule_shifts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/shifts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schedule_shifts_retrieve"];
        put: operations["schedule_shifts_update"];
        post?: never;
        delete: operations["schedule_shifts_destroy"];
        options?: never;
        head?: never;
        patch: operations["schedule_shifts_partial_update"];
        trace?: never;
    };
    "/api/v1/schedule/work-schedules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schedule_work_schedules_list"];
        put?: never;
        post: operations["schedule_work_schedules_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/work-schedules/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schedule_work_schedules_retrieve"];
        put: operations["schedule_work_schedules_update"];
        post?: never;
        delete: operations["schedule_work_schedules_destroy"];
        options?: never;
        head?: never;
        patch: operations["schedule_work_schedules_partial_update"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness check — process is up. */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Readiness check — dependencies (DB) reachable. */
        get: operations["health_ready_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `annual` - Annual
         *     * `monthly` - Monthly
         *     * `event_based` - Event-based
         *     * `none` - No accrual
         * @enum {string}
         */
        AccrualTypeEnum: "annual" | "monthly" | "event_based" | "none";
        /** @enum {unknown} */
        BlankEnum: "";
        Department: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            /** Format: uuid */
            parent?: string | null;
            /** Format: uuid */
            head_employee_id?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        DepartmentRequest: {
            name: string;
            /** Format: uuid */
            parent?: string | null;
            /** Format: uuid */
            head_employee_id?: string | null;
        };
        /** @description Full HR view — all fields readable; encrypted fields write-through. */
        Employee: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly org_id: string;
            /** Format: uuid */
            user?: string | null;
            employee_code: string;
            first_name: string;
            last_name: string;
            preferred_name?: string;
            readonly full_name: string;
            /** Format: email */
            email: string;
            phone: string;
            alt_phone?: string;
            readonly ic_last4: string;
            /** Format: date */
            date_of_birth: string;
            gender: components["schemas"]["GenderEnum"];
            nationality: string;
            marital_status: components["schemas"]["MaritalStatusEnum"];
            religion?: string;
            address_line1: string;
            address_line2?: string;
            city: string;
            state: string;
            postcode: string;
            country_code: string;
            /** Format: uuid */
            department: string;
            /** Format: uuid */
            manager?: string | null;
            role_title: string;
            employment_type: components["schemas"]["EmploymentTypeEnum"];
            schedule_type?: components["schemas"]["ScheduleTypeEnum"];
            /** Format: date */
            hire_date: string;
            /** Format: date */
            probation_end_date?: string | null;
            /** Format: date */
            contract_end_date?: string | null;
            /** Format: date-time */
            confirmed_at?: string | null;
            bank_name: string;
            readonly bank_account_last4: string;
            emergency_contact_name: string;
            emergency_contact_relationship: string;
            emergency_contact_phone: string;
            status?: components["schemas"]["EmployeeStatusEnum"];
            timezone?: string;
            locale?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Full HR view — all fields readable; encrypted fields write-through. */
        EmployeeRequest: {
            /** Format: uuid */
            user?: string | null;
            employee_code: string;
            first_name: string;
            last_name: string;
            preferred_name?: string;
            /** Format: email */
            email: string;
            phone: string;
            alt_phone?: string;
            /** Format: byte */
            ic_number?: string | null;
            /** Format: date */
            date_of_birth: string;
            gender: components["schemas"]["GenderEnum"];
            nationality: string;
            marital_status: components["schemas"]["MaritalStatusEnum"];
            religion?: string;
            address_line1: string;
            address_line2?: string;
            city: string;
            state: string;
            postcode: string;
            country_code: string;
            /** Format: uuid */
            department: string;
            /** Format: uuid */
            manager?: string | null;
            role_title: string;
            employment_type: components["schemas"]["EmploymentTypeEnum"];
            schedule_type?: components["schemas"]["ScheduleTypeEnum"];
            /** Format: date */
            hire_date: string;
            /** Format: date */
            probation_end_date?: string | null;
            /** Format: date */
            contract_end_date?: string | null;
            /** Format: date-time */
            confirmed_at?: string | null;
            bank_name: string;
            /** Format: byte */
            bank_account_number?: string | null;
            /** Format: byte */
            lhdn_tax_no?: string | null;
            /** Format: byte */
            epf_no?: string | null;
            /** Format: byte */
            socso_no?: string | null;
            /** Format: byte */
            eis_no?: string | null;
            emergency_contact_name: string;
            emergency_contact_relationship: string;
            emergency_contact_phone: string;
            status?: components["schemas"]["EmployeeStatusEnum"];
            timezone?: string;
            locale?: string;
        };
        /**
         * @description * `active` - Active
         *     * `probation` - Probation
         *     * `on_leave` - On leave
         *     * `terminated` - Terminated
         *     * `resigned` - Resigned
         * @enum {string}
         */
        EmployeeStatusEnum: "active" | "probation" | "on_leave" | "terminated" | "resigned";
        /**
         * @description * `fulltime` - Full-time
         *     * `parttime` - Part-time
         *     * `contract` - Contract
         *     * `intern` - Intern
         * @enum {string}
         */
        EmploymentTypeEnum: "fulltime" | "parttime" | "contract" | "intern";
        /**
         * @description * `male` - Male
         *     * `female` - Female
         *     * `other` - Other
         *     * `undisclosed` - Undisclosed
         * @enum {string}
         */
        GenderEnum: "male" | "female" | "other" | "undisclosed";
        /**
         * @description * `any` - Any
         *     * `male` - Male only
         *     * `female` - Female only
         * @enum {string}
         */
        GenderRestrictionEnum: "any" | "male" | "female";
        /**
         * @description * `am` - AM
         *     * `pm` - PM
         * @enum {string}
         */
        HalfDayPeriodEnum: "am" | "pm";
        Holiday: {
            /** Format: uuid */
            readonly id: string;
            /** Format: date */
            date: string;
            name: string;
            type: components["schemas"]["TypeEnum"];
            applies_to_country_code?: string;
            applies_to_state_code?: string;
        };
        HolidayRequest: {
            /** Format: date */
            date: string;
            name: string;
            type: components["schemas"]["TypeEnum"];
            applies_to_country_code?: string;
            applies_to_state_code?: string;
        };
        LeaveApproval: {
            readonly id: number;
            level: number;
            /** Format: uuid */
            approver_id: string;
            status?: components["schemas"]["LeaveApprovalStatusEnum"];
            comment?: string;
            /** Format: date-time */
            acted_at?: string | null;
            /** Format: uuid */
            delegated_to?: string | null;
        };
        LeaveApprovalRequest: {
            level: number;
            /** Format: uuid */
            approver_id: string;
            status?: components["schemas"]["LeaveApprovalStatusEnum"];
            comment?: string;
            /** Format: date-time */
            acted_at?: string | null;
            /** Format: uuid */
            delegated_to?: string | null;
        };
        /**
         * @description * `pending` - Pending
         *     * `approved` - Approved
         *     * `rejected` - Rejected
         *     * `delegated` - Delegated
         *     * `skipped` - Skipped
         * @enum {string}
         */
        LeaveApprovalStatusEnum: "pending" | "approved" | "rejected" | "delegated" | "skipped";
        LeaveBalance: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly employee_id: string;
            /** Format: uuid */
            readonly leave_type: string;
            readonly leave_type_code: string;
            readonly year: number;
            /** Format: decimal */
            readonly entitled: string;
            /** Format: decimal */
            readonly accrued: string;
            /** Format: decimal */
            readonly taken: string;
            /** Format: decimal */
            readonly pending: string;
            /** Format: decimal */
            readonly carried_forward: string;
            /** Format: decimal */
            readonly available: string;
        };
        LeaveRequest: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly org_id: string;
            /** Format: uuid */
            readonly employee_id: string;
            /** Format: uuid */
            leave_type: string;
            readonly leave_type_code: string;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
            /** Format: decimal */
            total_days: string;
            is_half_day?: boolean;
            half_day_period?: components["schemas"]["HalfDayPeriodEnum"] | components["schemas"]["BlankEnum"];
            reason?: string;
            /** Format: uri */
            attachment_url?: string;
            readonly status: components["schemas"]["LeaveStatusEnum"];
            readonly current_level: number;
            /** Format: date-time */
            readonly submitted_at: string | null;
            /** Format: date-time */
            readonly decided_at: string | null;
            /** Format: uuid */
            readonly decided_by: string | null;
            readonly approvals: components["schemas"]["LeaveApproval"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        LeaveRequestRequest: {
            /** Format: uuid */
            leave_type: string;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
            /** Format: decimal */
            total_days: string;
            is_half_day?: boolean;
            half_day_period?: components["schemas"]["HalfDayPeriodEnum"] | components["schemas"]["BlankEnum"];
            reason?: string;
            /** Format: uri */
            attachment_url?: string;
        };
        /**
         * @description * `draft` - Draft
         *     * `submitted` - Submitted
         *     * `approved` - Approved
         *     * `rejected` - Rejected
         *     * `cancelled` - Cancelled
         *     * `withdrawn` - Withdrawn
         * @enum {string}
         */
        LeaveStatusEnum: "draft" | "submitted" | "approved" | "rejected" | "cancelled" | "withdrawn";
        LeaveType: {
            /** Format: uuid */
            readonly id: string;
            code: string;
            name: string;
            accrual_type: components["schemas"]["AccrualTypeEnum"];
            /** Format: decimal */
            default_days?: string;
            is_paid?: boolean;
            requires_attachment?: boolean;
            max_consecutive_days?: number | null;
            min_advance_notice_days?: number;
            is_statutory?: boolean;
            gender_restriction?: components["schemas"]["GenderRestrictionEnum"];
        };
        /**
         * @description * `single` - Single
         *     * `married` - Married
         *     * `divorced` - Divorced
         *     * `widowed` - Widowed
         * @enum {string}
         */
        MaritalStatusEnum: "single" | "married" | "divorced" | "widowed";
        OrgSettings: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            readonly slug: string;
            country_code: string;
            default_currency: string;
            default_timezone: string;
            default_locale: string;
            settings?: unknown;
            readonly status: components["schemas"]["StatusEe8Enum"];
        };
        Organization: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug: string;
            country_code: string;
            default_currency: string;
            default_timezone: string;
            default_locale: string;
            settings?: unknown;
            status?: components["schemas"]["StatusEe8Enum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PatchedDepartmentRequest: {
            name?: string;
            /** Format: uuid */
            parent?: string | null;
            /** Format: uuid */
            head_employee_id?: string | null;
        };
        /** @description Full HR view — all fields readable; encrypted fields write-through. */
        PatchedEmployeeRequest: {
            /** Format: uuid */
            user?: string | null;
            employee_code?: string;
            first_name?: string;
            last_name?: string;
            preferred_name?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            alt_phone?: string;
            /** Format: byte */
            ic_number?: string | null;
            /** Format: date */
            date_of_birth?: string;
            gender?: components["schemas"]["GenderEnum"];
            nationality?: string;
            marital_status?: components["schemas"]["MaritalStatusEnum"];
            religion?: string;
            address_line1?: string;
            address_line2?: string;
            city?: string;
            state?: string;
            postcode?: string;
            country_code?: string;
            /** Format: uuid */
            department?: string;
            /** Format: uuid */
            manager?: string | null;
            role_title?: string;
            employment_type?: components["schemas"]["EmploymentTypeEnum"];
            schedule_type?: components["schemas"]["ScheduleTypeEnum"];
            /** Format: date */
            hire_date?: string;
            /** Format: date */
            probation_end_date?: string | null;
            /** Format: date */
            contract_end_date?: string | null;
            /** Format: date-time */
            confirmed_at?: string | null;
            bank_name?: string;
            /** Format: byte */
            bank_account_number?: string | null;
            /** Format: byte */
            lhdn_tax_no?: string | null;
            /** Format: byte */
            epf_no?: string | null;
            /** Format: byte */
            socso_no?: string | null;
            /** Format: byte */
            eis_no?: string | null;
            emergency_contact_name?: string;
            emergency_contact_relationship?: string;
            emergency_contact_phone?: string;
            status?: components["schemas"]["EmployeeStatusEnum"];
            timezone?: string;
            locale?: string;
        };
        PatchedHolidayRequest: {
            /** Format: date */
            date?: string;
            name?: string;
            type?: components["schemas"]["TypeEnum"];
            applies_to_country_code?: string;
            applies_to_state_code?: string;
        };
        PatchedLeaveRequestRequest: {
            /** Format: uuid */
            leave_type?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            /** Format: decimal */
            total_days?: string;
            is_half_day?: boolean;
            half_day_period?: components["schemas"]["HalfDayPeriodEnum"] | components["schemas"]["BlankEnum"];
            reason?: string;
            /** Format: uri */
            attachment_url?: string;
        };
        PatchedOrgSettingsRequest: {
            name?: string;
            country_code?: string;
            default_currency?: string;
            default_timezone?: string;
            default_locale?: string;
            settings?: unknown;
        };
        PatchedShiftAssignmentRequest: {
            /** Format: uuid */
            employee?: string;
            /** Format: uuid */
            shift?: string;
            /** Format: date */
            work_date?: string;
            status?: components["schemas"]["ShiftAssignmentStatusEnum"];
            /** Format: uuid */
            assigned_by?: string;
            notes?: string;
        };
        PatchedShiftRequest: {
            name?: string;
            /** Format: time */
            start_time?: string;
            /** Format: time */
            end_time?: string;
            crosses_midnight?: boolean;
            color?: string;
        };
        PatchedWorkScheduleRequest: {
            /** Format: uuid */
            employee?: string;
            name?: string;
            pattern?: unknown;
            /** Format: date */
            effective_from?: string;
            /** Format: date */
            effective_to?: string | null;
        };
        /**
         * @description * `fixed` - Fixed
         *     * `shift` - Shift
         * @enum {string}
         */
        ScheduleTypeEnum: "fixed" | "shift";
        Shift: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            /** Format: time */
            start_time: string;
            /** Format: time */
            end_time: string;
            crosses_midnight?: boolean;
            color?: string;
        };
        ShiftAssignment: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            employee: string;
            readonly employee_code: string;
            /** Format: uuid */
            shift: string;
            readonly shift_name: string;
            /** Format: date */
            work_date: string;
            status?: components["schemas"]["ShiftAssignmentStatusEnum"];
            /** Format: uuid */
            assigned_by: string;
            /** Format: date-time */
            readonly published_at: string | null;
            readonly is_published: boolean;
            notes?: string;
        };
        ShiftAssignmentRequest: {
            /** Format: uuid */
            employee: string;
            /** Format: uuid */
            shift: string;
            /** Format: date */
            work_date: string;
            status?: components["schemas"]["ShiftAssignmentStatusEnum"];
            /** Format: uuid */
            assigned_by: string;
            notes?: string;
        };
        /**
         * @description * `scheduled` - Scheduled
         *     * `completed` - Completed
         *     * `absent` - Absent
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        ShiftAssignmentStatusEnum: "scheduled" | "completed" | "absent" | "cancelled";
        ShiftRequest: {
            name: string;
            /** Format: time */
            start_time: string;
            /** Format: time */
            end_time: string;
            crosses_midnight?: boolean;
            color?: string;
        };
        /**
         * @description * `active` - Active
         *     * `suspended` - Suspended
         *     * `archived` - Archived
         * @enum {string}
         */
        StatusEe8Enum: "active" | "suspended" | "archived";
        /**
         * @description * `federal` - Federal
         *     * `state` - State
         *     * `company` - Company
         * @enum {string}
         */
        TypeEnum: "federal" | "state" | "company";
        WorkSchedule: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            employee: string;
            name?: string;
            pattern?: unknown;
            /** Format: date */
            effective_from: string;
            /** Format: date */
            effective_to?: string | null;
        };
        WorkScheduleRequest: {
            /** Format: uuid */
            employee: string;
            name?: string;
            pattern?: unknown;
            /** Format: date */
            effective_from: string;
            /** Format: date */
            effective_to?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_mfa_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_mfa_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_mfa_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_mfa_enable_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_forgot_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    departments_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"][];
                };
            };
        };
    };
    departments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentRequest"];
                "multipart/form-data": components["schemas"]["DepartmentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    departments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    departments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentRequest"];
                "multipart/form-data": components["schemas"]["DepartmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    departments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    departments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDepartmentRequest"];
                "multipart/form-data": components["schemas"]["PatchedDepartmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    employees_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"][];
                };
            };
        };
    };
    employees_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeRequest"];
                "multipart/form-data": components["schemas"]["EmployeeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    employees_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    employees_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeRequest"];
                "multipart/form-data": components["schemas"]["EmployeeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    employees_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    employees_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEmployeeRequest"];
                "multipart/form-data": components["schemas"]["PatchedEmployeeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    employees_direct_reports_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    employees_probation_status_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    employees_reporting_chain_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    employees_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    employees_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEmployeeRequest"];
                "multipart/form-data": components["schemas"]["PatchedEmployeeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    leave_balances_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveBalance"][];
                };
            };
        };
    };
    leave_balances_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveBalance"];
                };
            };
        };
    };
    leave_balances_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveBalance"];
                };
            };
        };
    };
    leave_requests_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequest"][];
                };
            };
        };
    };
    leave_requests_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveRequestRequest"];
                "multipart/form-data": components["schemas"]["LeaveRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequest"];
                };
            };
        };
    };
    leave_requests_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequest"];
                };
            };
        };
    };
    leave_requests_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveRequestRequest"];
                "multipart/form-data": components["schemas"]["LeaveRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequest"];
                };
            };
        };
    };
    leave_requests_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    leave_requests_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedLeaveRequestRequest"];
                "multipart/form-data": components["schemas"]["PatchedLeaveRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequest"];
                };
            };
        };
    };
    leave_requests_approve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveRequestRequest"];
                "multipart/form-data": components["schemas"]["LeaveRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequest"];
                };
            };
        };
    };
    leave_requests_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveRequestRequest"];
                "multipart/form-data": components["schemas"]["LeaveRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequest"];
                };
            };
        };
    };
    leave_requests_reject_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveRequestRequest"];
                "multipart/form-data": components["schemas"]["LeaveRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequest"];
                };
            };
        };
    };
    leave_requests_submit_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveRequestRequest"];
                "multipart/form-data": components["schemas"]["LeaveRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequest"];
                };
            };
        };
    };
    leave_requests_withdraw_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveRequestRequest"];
                "multipart/form-data": components["schemas"]["LeaveRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveRequest"];
                };
            };
        };
    };
    leave_types_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveType"][];
                };
            };
        };
    };
    leave_types_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaveType"];
                };
            };
        };
    };
    org_settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSettings"];
                };
            };
        };
    };
    org_settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedOrgSettingsRequest"];
                "multipart/form-data": components["schemas"]["PatchedOrgSettingsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSettings"];
                };
            };
        };
    };
    organizations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"][];
                };
            };
        };
    };
    organizations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    schedule_holidays_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holiday"][];
                };
            };
        };
    };
    schedule_holidays_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HolidayRequest"];
                "multipart/form-data": components["schemas"]["HolidayRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holiday"];
                };
            };
        };
    };
    schedule_holidays_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holiday"];
                };
            };
        };
    };
    schedule_holidays_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HolidayRequest"];
                "multipart/form-data": components["schemas"]["HolidayRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holiday"];
                };
            };
        };
    };
    schedule_holidays_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    schedule_holidays_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedHolidayRequest"];
                "multipart/form-data": components["schemas"]["PatchedHolidayRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holiday"];
                };
            };
        };
    };
    schedule_shift_assignments_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftAssignment"][];
                };
            };
        };
    };
    schedule_shift_assignments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftAssignmentRequest"];
                "multipart/form-data": components["schemas"]["ShiftAssignmentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftAssignment"];
                };
            };
        };
    };
    schedule_shift_assignments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftAssignment"];
                };
            };
        };
    };
    schedule_shift_assignments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftAssignmentRequest"];
                "multipart/form-data": components["schemas"]["ShiftAssignmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftAssignment"];
                };
            };
        };
    };
    schedule_shift_assignments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    schedule_shift_assignments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedShiftAssignmentRequest"];
                "multipart/form-data": components["schemas"]["PatchedShiftAssignmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftAssignment"];
                };
            };
        };
    };
    schedule_shift_assignments_bulk_pattern_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftAssignmentRequest"];
                "multipart/form-data": components["schemas"]["ShiftAssignmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftAssignment"];
                };
            };
        };
    };
    schedule_shift_assignments_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftAssignment"];
                };
            };
        };
    };
    schedule_shift_assignments_publish_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftAssignmentRequest"];
                "multipart/form-data": components["schemas"]["ShiftAssignmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftAssignment"];
                };
            };
        };
    };
    schedule_shifts_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"][];
                };
            };
        };
    };
    schedule_shifts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftRequest"];
                "multipart/form-data": components["schemas"]["ShiftRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
        };
    };
    schedule_shifts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
        };
    };
    schedule_shifts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftRequest"];
                "multipart/form-data": components["schemas"]["ShiftRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
        };
    };
    schedule_shifts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    schedule_shifts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedShiftRequest"];
                "multipart/form-data": components["schemas"]["PatchedShiftRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
        };
    };
    schedule_work_schedules_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkSchedule"][];
                };
            };
        };
    };
    schedule_work_schedules_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkScheduleRequest"];
                "multipart/form-data": components["schemas"]["WorkScheduleRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkSchedule"];
                };
            };
        };
    };
    schedule_work_schedules_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkSchedule"];
                };
            };
        };
    };
    schedule_work_schedules_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkScheduleRequest"];
                "multipart/form-data": components["schemas"]["WorkScheduleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkSchedule"];
                };
            };
        };
    };
    schedule_work_schedules_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    schedule_work_schedules_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedWorkScheduleRequest"];
                "multipart/form-data": components["schemas"]["PatchedWorkScheduleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkSchedule"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_ready_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
