# Generated by Django 5.0.14 on 2026-04-27 17:01

import django.utils.timezone
import modules.identity.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('locked', 'Locked')], default='active', max_length=16)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('failed_login_count', models.IntegerField(default=0)),
                ('preferences', models.JSONField(blank=True, default=modules.identity.models._default_preferences)),
                ('consents', models.JSONField(blank=True, default=modules.identity.models._default_consents)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'identity_user',
                'indexes': [models.Index(fields=['org_id'], name='identity_us_org_id_511043_idx'), models.Index(fields=['email'], name='identity_us_email_bcdd3b_idx')],
            },
            managers=[
                ('objects', modules.identity.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('org_id', 'email'), name='user_unique_email_per_org'),
        ),
    ]
