# Generated by Django 5.0.14 on 2026-06-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sent_to_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
