# Generated by Django 5.0.14 on 2026-06-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_invitation_sent_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_dangerous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='label',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='permission',
            name='requires',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
