# Generated by Django 5.0.14 on 2026-04-27 22:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('work_date', models.DateField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('kiosk', 'Kiosk'), ('mobile', 'Mobile'), ('admin', 'Admin')], default='web', max_length=8)),
                ('is_holiday_work', models.BooleanField(default=False)),
                ('holiday_id', models.UUIDField(blank=True, null=True)),
                ('shift_assignment_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('holiday', 'Holiday'), ('on_leave', 'On leave'), ('partial', 'Partial')], default='absent', max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employee.employee')),
            ],
            options={
                'db_table': 'attendance_record',
                'indexes': [models.Index(fields=['org_id', 'employee', '-work_date'], name='attendance__org_id_de3f76_idx'), models.Index(fields=['org_id', 'work_date'], name='attendance__org_id_d9fbd7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee', 'work_date'), name='attendance_unique_emp_date'),
        ),
    ]
