# Generated by Django 5.0.14 on 2026-04-27 23:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('required_for_role_id', models.UUIDField(blank=True, null=True)),
                ('required_for_dept_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training_plan',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('employee_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('issued_on', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('document_s3_key', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('reminder_sent_30d', models.BooleanField(default=False)),
                ('reminder_sent_60d', models.BooleanField(default=False)),
                ('reminder_sent_90d', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'certification',
                'indexes': [models.Index(fields=['employee_id'], name='certificati_employe_a14681_idx'), models.Index(fields=['org_id', 'expires_on'], name='certificati_org_id_c73f69_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('employee_id', models.UUIDField()),
                ('assigned_by', models.UUIDField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='assigned', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_s3_key', models.CharField(blank=True, max_length=500)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='certification.trainingplan')),
            ],
            options={
                'db_table': 'training_assignment',
            },
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='certification.trainingassignment')),
            ],
            options={
                'db_table': 'training_progress',
            },
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['employee_id', 'status'], name='training_as_employe_1adeee_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['org_id', 'status'], name='training_as_org_id_764f8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('plan', 'employee_id'), name='training_assignment_unique_plan_emp'),
        ),
        migrations.AddIndex(
            model_name='trainingprogress',
            index=models.Index(fields=['assignment', '-ts'], name='training_pr_assignm_03a7dd_idx'),
        ),
    ]
