# Generated by Django 5.0.14 on 2026-04-27 22:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=64)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'db_table': 'schedule_shift',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('work_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('assigned_by', models.UUIDField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'schedule_shift_assignment',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(default='Default', max_length=64)),
                ('pattern', models.JSONField(default=dict)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedule_work_schedule',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('company', 'Company')], max_length=8)),
                ('applies_to_country_code', models.CharField(blank=True, max_length=2)),
                ('applies_to_state_code', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'db_table': 'schedule_holiday',
                'indexes': [models.Index(fields=['org_id', 'date'], name='schedule_ho_org_id_0661ec_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('org_id', 'date', 'name'), name='holiday_unique_org_date_name'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('org_id', 'name'), name='shift_unique_name_per_org'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='schedule.shift'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='employee.employee'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['org_id', 'work_date'], name='schedule_sh_org_id_ca55d0_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['employee', 'work_date'], name='schedule_sh_employe_3fdb93_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['shift', 'work_date'], name='schedule_sh_shift_i_108d95_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee', 'work_date'), name='shift_assignment_unique_emp_date'),
        ),
        migrations.AddIndex(
            model_name='workschedule',
            index=models.Index(fields=['employee', 'effective_from'], name='schedule_wo_employe_44c427_idx'),
        ),
    ]
