# Generated by Django 5.0.14 on 2026-05-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_team'),
        ('schedule', '0002_shift_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='covering_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_by', to='employee.employee'),
        ),
    ]
