# Generated by Django 5.0.14 on 2026-08-18 09:20

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("employee", "0007_employee_contract_alert_sent_and_more"),
        ("schedule", "0003_covering_for"),
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="ShiftSwapRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("org_id", models.UUIDField(db_index=True, editable=False)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decided_by", models.UUIDField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True, default="")),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="swap_requests_received",
                        to="employee.employee",
                    ),
                ),
                (
                    "counterparty_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="swap_requests_received",
                        to="schedule.shiftassignment",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="swap_requests_made",
                        to="employee.employee",
                    ),
                ),
                (
                    "requester_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="swap_requests_made",
                        to="schedule.shiftassignment",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_shift_swap_request",
                "indexes": [
                    models.Index(fields=["org_id", "status"], name="schedule_sh_org_id_b5b41d_idx"),
                    models.Index(
                        fields=["requester", "-created_at"], name="schedule_sh_request_9d0ed3_idx"
                    ),
                    models.Index(
                        fields=["counterparty", "-created_at"],
                        name="schedule_sh_counter_82f661_idx",
                    ),
                ],
            },
        ),
    ]
