# Generated by Django 5.0.14 on 2026-08-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_shift_swap_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='applies_to_subdivision_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='holiday',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holiday',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='observed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holiday',
            name='provisional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holiday',
            name='source',
            field=models.CharField(choices=[('company', 'Company-created'), ('override', 'Organization override'), ('import', 'Imported from provider'), ('legacy', 'Legacy fixture')], default='legacy', max_length=16),
        ),
        migrations.AddField(
            model_name='holiday',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='holiday',
            name='source_provider',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='holiday',
            name='source_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('source_key', ''), _negated=True)), fields=('org_id', 'source_key'), name='holiday_unique_org_source_key'),
        ),
    ]
