# Generated by Django 5.0.14 on 2026-08-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_holiday_applies_to_subdivision_code_holiday_excluded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='confirmed_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='external_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='holiday',
            name='occurrence',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
