# Generated by Django 5.0.14 on 2026-04-27 21:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('employee_id', models.UUIDField()),
                ('year', models.IntegerField()),
                ('entitled', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('accrued', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('taken', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('pending', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('carried_forward', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
            ],
            options={
                'db_table': 'leave_balance',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalanceLedger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('employee_id', models.UUIDField()),
                ('delta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.CharField(choices=[('accrual', 'Accrual'), ('request_approved', 'Request approved'), ('request_cancelled', 'Request cancelled'), ('carry_forward', 'Carry forward'), ('holiday_replacement', 'Holiday replacement'), ('manual_adjustment', 'Manual adjustment')], max_length=32)),
                ('reference_type', models.CharField(blank=True, max_length=64, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'leave_balance_ledger',
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('applies_to_role_id', models.UUIDField(blank=True, null=True)),
                ('applies_to_department_id', models.UUIDField(blank=True, null=True)),
                ('days_per_year', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenure_brackets', models.JSONField(blank=True, default=list)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leave_policy',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('accrual_type', models.CharField(choices=[('annual', 'Annual'), ('monthly', 'Monthly'), ('event_based', 'Event-based'), ('none', 'No accrual')], max_length=16)),
                ('default_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_attachment', models.BooleanField(default=False)),
                ('max_consecutive_days', models.IntegerField(blank=True, null=True)),
                ('min_advance_notice_days', models.IntegerField(default=0)),
                ('carry_forward_max', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('is_statutory', models.BooleanField(default=False)),
                ('gender_restriction', models.CharField(choices=[('any', 'Any'), ('male', 'Male only'), ('female', 'Female only')], default='any', max_length=8)),
            ],
            options={
                'db_table': 'leave_type',
            },
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('org_id', 'code'), name='leave_type_unique_code_per_org'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='leave.leavetype'),
        ),
        migrations.AddField(
            model_name='leavebalanceledger',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='leave.leavetype'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='leave.leavetype'),
        ),
        migrations.AddIndex(
            model_name='leavepolicy',
            index=models.Index(fields=['leave_type', 'effective_from'], name='leave_polic_leave_t_824ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalanceledger',
            index=models.Index(fields=['employee_id', 'leave_type', '-ts'], name='leave_balan_employe_da30c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavebalanceledger',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('reference_type', None), _negated=True), models.Q(('reference_id', None), _negated=True)), fields=('reference_type', 'reference_id', 'reason'), name='leave_ledger_unique_per_reference'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['employee_id', 'year'], name='leave_balan_employe_3c91bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee_id', 'leave_type', 'year'), name='leave_balance_unique_emp_type_year'),
        ),
    ]
