# Generated by Django 5.0.14 on 2026-04-27 21:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('employee_id', models.UUIDField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_period', models.CharField(blank=True, choices=[('am', 'AM'), ('pm', 'PM')], max_length=2)),
                ('reason', models.TextField(blank=True)),
                ('attachment_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
                ('current_level', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.UUIDField(blank=True, null=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave.leavetype')),
            ],
            options={
                'db_table': 'leave_request',
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('approver_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delegated', 'Delegated'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('delegated_to', models.UUIDField(blank=True, null=True)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leave.leaverequest')),
            ],
            options={
                'db_table': 'leave_approval',
            },
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee_id', '-submitted_at'], name='leave_reque_employe_edf1d4_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'current_level'], name='leave_reque_status_31d12c_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['org_id', 'status'], name='leave_reque_org_id_c2785f_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapproval',
            index=models.Index(fields=['leave_request', 'level'], name='leave_appro_leave_r_ff2578_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapproval',
            index=models.Index(fields=['approver_id', 'status'], name='leave_appro_approve_adebcb_idx'),
        ),
    ]
