# Generated by Django 5.0.14 on 2026-05-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaverequest_leaveapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward_expiry_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_per_lifetime_events',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='notice_days_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_service_months',
            field=models.IntegerField(default=0),
        ),
    ]
