# Generated by Django 5.0.14 on 2026-05-07 16:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leave_type_carry_expiry_and_eligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('employee_id', models.UUIDField()),
                ('days_override', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='leave.leavetype')),
            ],
            options={
                'db_table': 'employee_leave_override',
                'indexes': [models.Index(fields=['employee_id', 'leave_type'], name='employee_le_employe_12e059_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeeleaveoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee_id', 'leave_type', 'effective_from'), name='emp_leave_override_unique'),
        ),
    ]
