# Generated by Django 5.0.14 on 2026-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_employee_leave_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='carried_forward_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
