# Generated by Django 5.0.14 on 2026-04-27 23:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KpiCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual')], max_length=16)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('review_opens_on', models.DateField()),
                ('review_closes_on', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('self_review', 'Self review'), ('manager_review', 'Manager review'), ('closed', 'Closed')], default='upcoming', max_length=20)),
            ],
            options={
                'db_table': 'kpi_cycle',
                'indexes': [models.Index(fields=['org_id', '-starts_on'], name='kpi_cycle_org_id_4af041_idx')],
            },
        ),
        migrations.CreateModel(
            name='KpiAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('employee_id', models.UUIDField()),
                ('kpis', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('self_done', 'Self done'), ('manager_done', 'Manager done'), ('closed', 'Closed')], default='pending', max_length=16)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='kpi.kpicycle')),
            ],
            options={
                'db_table': 'kpi_assignment',
            },
        ),
        migrations.CreateModel(
            name='KpiReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iteration', models.IntegerField(default=1)),
                ('stage', models.CharField(choices=[('self', 'Self'), ('manager', 'Manager'), ('final', 'Final')], max_length=8)),
                ('scores', models.JSONField(default=dict)),
                ('overall_comment', models.TextField(blank=True)),
                ('evidence', models.JSONField(default=list)),
                ('submitted_by', models.UUIDField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ai_summary_id', models.UUIDField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='kpi.kpiassignment')),
            ],
            options={
                'db_table': 'kpi_review',
            },
        ),
        migrations.CreateModel(
            name='KpiReviewIteration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('change_summary', models.JSONField(default=dict)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='kpi.kpireview')),
            ],
            options={
                'db_table': 'kpi_review_iteration',
            },
        ),
        migrations.CreateModel(
            name='KpiTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('applies_to_role_id', models.UUIDField(blank=True, null=True)),
                ('applies_to_dept_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kpi_template',
                'indexes': [models.Index(fields=['org_id'], name='kpi_templat_org_id_0022e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='KpiDefinition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('numeric', 'Numeric'), ('percentage', 'Percentage'), ('rating', 'Rating'), ('boolean', 'Boolean')], max_length=16)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('evidence_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='kpi.kpitemplate')),
            ],
            options={
                'db_table': 'kpi_definition',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='kpiassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='kpi.kpitemplate'),
        ),
        migrations.AddIndex(
            model_name='kpireview',
            index=models.Index(fields=['assignment', 'iteration'], name='kpi_review_assignm_c53756_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpidefinition',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='kpi_def_unique_code_per_template'),
        ),
        migrations.AddIndex(
            model_name='kpiassignment',
            index=models.Index(fields=['employee_id', 'cycle'], name='kpi_assignm_employe_a0037d_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpiassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('cycle', 'employee_id'), name='kpi_assignment_unique_cycle_emp'),
        ),
    ]
