# Generated by Django 5.0.14 on 2026-07-12 14:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_id', models.UUIDField(db_index=True, editable=False)),
                ('category', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('improvement', 'Improvement/Enhancement'), ('uiux', 'UI/UX Feedback'), ('performance', 'Performance Issue'), ('security', 'Security Concern'), ('documentation', 'Documentation Issue'), ('general', 'General Feedback')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('affected_module', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=16)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_assigned', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('s3_key', models.CharField(max_length=500)),
                ('uploaded_by', models.UUIDField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedback')),
            ],
            options={
                'db_table': 'feedback_attachment',
            },
        ),
        migrations.CreateModel(
            name='FeedbackNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.UUIDField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='feedback.feedback')),
            ],
            options={
                'db_table': 'feedback_note',
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['org_id', 'status'], name='feedback_org_id_a4f963_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['reporter', '-created_at'], name='feedback_reporte_da391b_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['org_id', '-created_at'], name='feedback_org_id_6bbe78_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacknote',
            index=models.Index(fields=['feedback', 'created_at'], name='feedback_no_feedbac_ade484_idx'),
        ),
    ]
